spring:
  jpa:
    generate-ddl: 'false'
    database: postgresql
    show-sql: 'false'
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        format_sql: 'true'
        id:
          new_generator_mappings: 'false'
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  data:
    rest:
      base-path: /api
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout:
      seconds: '900'
#spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  datasource:
    username: postgres
    password: 1q2q3q
    driver-class-name: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:h2:file:./demo
#    data: create_test_data.sql

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: 'false'
logging:
  level:
    com:
      stbegradleapp: DEBUG
#server:
#  port: '8050'

# App Properties
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000
